### ISSUE TITLE
Idea: inject syntax highlighting for Editor windows

### ISSUE THREAD

**Issue by mutterer** [mutterer/open-in-imagej-js-extension#7]
It would be nice to inject some syntax highlighting script that would take care of Macro Editor instances.
Highlight.js seems to do that: https://highlightjs.org/
It does not support <textarea> directly, but this seems possible, see working example at: https://codepen.io/shotastage/pen/KaKwya

**Comment by oeway** [comment]
Hey, good idea!

I already implemented something like that with codemirror, and you can
check it by Plugins-> New -> and choose any of the ImJoy plugin.

I disabled it for macro at the moment,  the issue I had is that I don’t
know how to detect what language it was written in. Perhaps we can use the
file name in the title?

Also is there a syntax highlighting for imagej macro? Otherwise we can use
the javascript ?

**Comment by oeway** [comment]
Wait, do you mean you want to do it for Github and Gist? For that, we can also contribute a language highlighting direct to Github, that will enable syntax highlighting for all the .ijm files.

The repo: https://github.com/github/linguist
Contribution guideline: https://github.com/github/linguist/blob/master/CONTRIBUTING.md

**Comment by mutterer** [comment]
No I was suggesting for the macros in ij.imjoy.io
What you did for the imjoy plugin looks great! Yes inferring from the file name extension could provide the highlighter to use, .txt and .ijm for macros (works nicely with javascript highlighter)
I see that python, javascript and beanshell examples do not work out of the box so far. 

Thanks for the links to github linguist, it would be nice to have, I look into it (lockdown project?)

**Comment by oeway** [comment]
> No I was suggesting for the macros in ij.imjoy.io

Good, I will make that happen.

> I see that python, javascript and beanshell examples do not work out of the box so far.

Right, we don't support python and javascript, nor beanshell, jython for example, will need additional package, javascript(java flavoured) is not supported because the js engine has been removed from the java runtime, beanshell will also need additional packages.
The other thing that jython has no python 3 version, which makes it less attractive to support. We may look more into this in the ImageJ2 version. For now, the plan is to extend other script via ImJoy, which can easily provide full python(CPython+Numpy, Scipy etc.) integration.

**Comment by oeway** [comment]
Made a PR: https://github.com/imjoy-team/imagej.js/pull/30

And here is a preview version: https://deploy-preview-30--imagej.netlify.app/

<img width="893" alt="Screenshot 2020-11-01 at 18 43 15" src="https://user-images.githubusercontent.com/478667/97810160-25be2580-1c72-11eb-88ae-c45bdfe523d8.png">

**Comment by mutterer** [comment]
Syntax highlighting works nicely when you open an existing file, but it appears to block typing in new macros, eg those created using Plugin>New>Macro.
